### ISSUE TITLE
`book sm g`后面加任何参数都不生成`SUMMARY.md`

### ISSUE THREAD

**Issue by GreedBell** [imfly/gitbook-summary#2]
例如:`$ book sm g -n "Your Book Name"`,没生成`SUMMARY.md`也没有任何提示。

**Comment by imfly** [comment]
@GreedBell 感谢反馈，之前发现了这个问题，因为各种原因，一直没修改。你重新安装或更新一下，试试看。

**Comment by GreedBell** [comment]
`$ book -i test sm g` 报下面的错误。

```
/usr/local/lib/node_modules/gitbook-summary/lib/index.js:50
            ignores.push(_.trim(outputFile, '.md'));
                    ^
TypeError: undefined is not a function
    at Array.async.auto.init (/usr/local/lib/node_modules/gitbook-summary/lib/index.js:50:21)
    at /usr/local/lib/node_modules/gitbook-summary/node_modules/async/lib/async.js:596:38
    at _arrayEach (/usr/local/lib/node_modules/gitbook-summary/node_modules/async/lib/async.js:85:13)
    at Object.async.auto (/usr/local/lib/node_modules/gitbook-summary/node_modules/async/lib/async.js:554:9)
    at Object.summary (/usr/local/lib/node_modules/gitbook-summary/lib/index.js:45:11)
    at Command.<anonymous> (/usr/local/lib/node_modules/gitbook-summary/bin/summary.js:29:18)
    at Command.listener (/usr/local/lib/node_modules/gitbook-summary/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/gitbook-summary/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/gitbook-summary/node_modules/commander/index.js:458:21)
```

**Comment by imfly** [comment]
仅仅为了自己用才开发这个东东，看来即便这样，也要认真对待才不会出现这类低级错误。

**Comment by GreedBell** [comment]
这就是Github的好处，方便了别人，也得到了免费测试。3Q!
