### ISSUE TITLE
在book.jason中排除无关文件，运行book sm 提示失败

### ISSUE THREAD

**Issue by fang-yu** [imfly/gitbook-summary#28]
Hi：

感谢你的共享的插件。我在部署的过程中，因为默认`book sm`会把node module 和_book的都收录到目录里面，想要把这两个目录排除，因此我在`book.json`中增加了如下代码：

```
{
    "bookname": "json-config-name",
    "outputfile": "test.md",
    "catalog": "all",  // 如 [chapter1，chapter2, ...]
    "ignores": [],
    "unchanged": [] // 如: ['myApp'] -> `myApp` not `My App`
}
```

但是再次运行book sm的时候，提示以下错误：

```
module.js:682
    throw err;
    ^

SyntaxError: ……/testbook/book.json: Unexpected token / in JSON at position 87
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at BookConfig (/Users/aban/.nvm/versions/node/v9.5.0/lib/node_modules/gitbook-summary/lib/bookJson.js:10:18)
    at init (/Users/aban/.nvm/versions/node/v9.5.0/lib/node_modules/gitbook-summary/lib/summary/index.js:29:22)
    at Array.init (/Users/aban/.nvm/versions/node/v9.5.0/lib/node_modules/gitbook-summary/lib/summary/index.js:51:13)

```

相关的配置信息：
- Mac
- Node版本：7.1.0
- npm版本：3.10.9
- Gitbook CLI 版本: 2.3.2

**Comment by anlia260** [comment]
ignores 更改下忽略目录就好。

![image](https://user-images.githubusercontent.com/11311553/36655412-789f8fec-1afd-11e8-8fb2-721b0e74f0f0.png)
